name: hmb
description: "Hold My Beer. Customer, Job management and billing for solo trades people."
publish_to: 'none'

# The following defines the version and build number for your application.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 0.12.8

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  app_links: ^6.1.4
  archive: ^4.0.4
  calendar_view:
    hosted: https://onepub.dev/api/jbbxpsdavu/
    version: ^1.3.2
  camera_platform_interface: ^2.8.0
  camera_windows: ^0.2.6
  completer_ex: ^4.0.3
  country_code2: ^2.0.0
  date_time_format: ^2.0.1
  datetime_picker_formfield_new : ^2.0.1
  dcli: ^7.0.1
  dcli_core: ^7.0.1
  deferred_state: ^1.0.0
  direct_caller_sim_choice: ^1.0.5
  dlibphonenumber: ^1.1.18
  email_validator: ^3.0.0
  equatable: ^2.0.0
  ffi: ^2.1.2
  file_picker: ^10.1.2
  fixed: ^6.0.0
  fleather: ^1.17.0
  flutter:
    sdk: flutter

  flutter_colorpicker: ^1.1.0
  flutter_email_sender: ^7.0.0
  flutter_image_compress: ^2.4.0
  flutter_local_notifications: ^19.4.0
  flutter_native_timezone_2025: ^1.0.1
  flutter_secure_storage: ^10.0.0-beta.4
  flutter_secure_storage_linux: ^2.0.1
  flutter_svg: ^2.0.14
  fsm2: ^3.3.0
  future_builder_ex: ^5.0.0
  go_router: ^16.0.0
  # removed as it's no 16kb page aligned.
  # google_mlkit_barcode_scanning: ^0.14.1
  google_sign_in: ^7.1.0
  # extension_google_sign_in_as_googleapis_auth: 3.0.0
  googleapis: ^14.0.0
  # googleapis_auth: ^2.0.0
  halfpipe: ^1.0.1
  http: ^1.2.1
  image: ^4.5.4
  image_picker: ^1.1.1
  image_picker_platform_interface: ^2.10.0
  image_picker_windows: ^0.2.1+1
  infinite_calendar_view: ^2.4.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  june: ^1.0.0+1
  logger: ^2.4.0
  mailto: ^2.0.0
  # mobile_number: ^2.1.1
  meta: ^1.16.0
  
  money2: ^6.0.5
  oauth2: ^2.0.3
  package_info_plus: ^8.1.1
  parchment_delta: ^1.0.0
  pasteboard: ^0.4.0
  path: ^1.9.0
  path_provider: ^2.0.0
  pdf: ^3.11.0
  pdfrx: ^2.1.3
  permission_handler: ^12.0.0+1
  photo_view: ^0.15.0
  printing: ^5.13.1
  provider: ^6.1.2
  scope: ^5.1.0
  sentry: ^9.1.0
  sentry_flutter: ^9.1.0
  # sms_advanced: # ^1.1.0
  #   hosted: https://onepub.dev/api/jbbxpsdavu/
  settings_yaml: ^8.3.0
  sqflite: ^2.3.2
  sqflite_common: ^2.5.4+5
  sqflite_common_ffi: ^2.3.3+1
  sqflite_common_ffi_web: ^1.0.0
  stacktrace_impl: ^2.3.0
  strings: ^4.0.1
  svg_flutter: ^0.0.1
  time_machine: ^0.9.17
  timezone: ^0.10.1
  toastification: ^3.0.1
  url_launcher: ^6.2.5
  wakelock_plus: ^1.2.8
  win32: ^5.5.1
  zoom_view: ^0.0.24

dev_dependencies:
  args: ^2.5.0
  flutter_launcher_icons: ^0.14.0
  flutter_test:
    sdk: flutter
  lint_hard: ^6.2.1
  mockito: ^5.4.4
  pub_release: ^11.0.0
  pubspec_manager: ^1.0.0
  test: ^1.25.15

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/sql/upgrade_scripts/
    - assets/sql/upgrade_list.json
    - assets/installer/linux/hmb.desktop


flutter_icons:
  android: true
  ios: true
  macos: true
  windows: true
  linux: true
  web: true
  image_path: "assets/icons/hmb_app_icon.webp"
