// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyzQLYmZBrmRrgKhoFCh7GMJI64aKW5sY',
    appId: '1:867590954038:web:1928d29f7b070e9a5d4c97',
    messagingSenderId: '867590954038',
    projectId: 'hold-my-beer-ed8ee',
    authDomain: 'hold-my-beer-ed8ee.firebaseapp.com',
    storageBucket: 'hold-my-beer-ed8ee.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfbY5gGD36lBqKYHAIRanXR7UWesZBqF8',
    appId: '1:867590954038:android:95bc2dc5d9ce4a8d5d4c97',
    messagingSenderId: '867590954038',
    projectId: 'hold-my-beer-ed8ee',
    storageBucket: 'hold-my-beer-ed8ee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnW9xF58Z6KX2vpn2D6I8aISM2yM53C6I',
    appId: '1:867590954038:ios:b7498284b25b1f3e5d4c97',
    messagingSenderId: '867590954038',
    projectId: 'hold-my-beer-ed8ee',
    storageBucket: 'hold-my-beer-ed8ee.appspot.com',
    iosBundleId: 'dev.onepub.handyman',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnW9xF58Z6KX2vpn2D6I8aISM2yM53C6I',
    appId: '1:867590954038:ios:b7498284b25b1f3e5d4c97',
    messagingSenderId: '867590954038',
    projectId: 'hold-my-beer-ed8ee',
    storageBucket: 'hold-my-beer-ed8ee.appspot.com',
    iosBundleId: 'dev.onepub.handyman',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyzQLYmZBrmRrgKhoFCh7GMJI64aKW5sY',
    appId: '1:867590954038:web:e37ef396744743095d4c97',
    messagingSenderId: '867590954038',
    projectId: 'hold-my-beer-ed8ee',
    authDomain: 'hold-my-beer-ed8ee.firebaseapp.com',
    storageBucket: 'hold-my-beer-ed8ee.appspot.com',
  );
}
