#! /usr/bin/env dart

// ignore: unused_import
import 'package:dcli/dcli.dart';
// import 'package:hmb/util/local_date.dart';
import 'package:path/path.dart';

/// dcli script generated by:
/// dcli create %scriptname%
///
/// See
/// https://pub.dev/packages/dcli#-installing-tab-
///
/// For details on installing dcli.
///
void main(List<String> args) {
  final pathToDb = join(
    DartProject.self.pathToProjectRoot,
    '.dart_tool',
    'sqflite_common_ffi',
    'databases',
  );
  move(
    join(pathToDb, 'handyman.db'),
    join(pathToDb, 'handyman.db.${DateTime.now()}'),
  );
}
