#! /usr/bin/env dart
/*
 Copyright © OnePub IP Pty Ltd. S. Brett Sutton. All Rights Reserved.

 Note: This software is licensed under the GNU General Public License,
         with the following exceptions:
   • Permitted for internal use within your own business or organization only.
   • Any external distribution, resale, or incorporation into products 
      for third parties is strictly prohibited.

 See the full license on GitHub:
 https://github.com/bsutton/hmb/blob/main/LICENSE
*/

import 'package:dcli/dcli.dart';
// import 'package:hmb/util/local_date.dart';
import 'package:path/path.dart';

/// dcli script generated by:
/// dcli create %scriptname%
///
/// See
/// https://pub.dev/packages/dcli#-installing-tab-
///
/// For details on installing dcli.
///
void main(List<String> args) {
  final pathToDb = join(
    DartProject.self.pathToProjectRoot,
    '.dart_tool',
    'sqflite_common_ffi',
    'databases',
  );
  move(
    join(pathToDb, 'handyman.db'),
    join(pathToDb, 'handyman.db.${DateTime.now()}'),
  );

  // await pathToHmbFiles
  /// correct until its not. We can't use [pathToHmbFiles] as this requires
  /// flutter
  delete(
    join(
      '/home/bsutton/snap/code/187/.local/share/dev.onepub.handyman/hmb',
      'firstrun.txt',
    ),
  );
}
