ALTER TABLE job
ADD COLUMN estimate_margin INTEGER NOT NULL DEFAULT 0;

ALTER TABLE quote
ADD COLUMN quote_margin INTEGER NOT NULL DEFAULT 0;

ALTER TABLE quote_line_group
ADD COLUMN task_margin INTEGER NOT NULL DEFAULT 0;
