CREATE TABLE version (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    db_version INTEGER NOT NULL,
    code_version TEXT NOT NULL,
    created_date TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_date TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);